import dataclasses

import fpdf
import base64
import re
import io
import xml.etree.ElementTree as ET

from mistletoe import markdown
from fpdf.html import FontFace, TextStyle

from PIL import Image
from pathlib import Path
from typing import Any, Dict, List, Tuple, Optional

FONTS_DIR = Path(__file__).parent / "fonts"
REFACT_LOGO_SVG = (Path(__file__).parent / "assets" / "refact_logo.svg").read_text().strip()
REFACT_LOGO_SMALL_SVG = (Path(__file__).parent / "assets" / "refact_logo_small.svg").read_text().strip()
BACKGROUND_SVGS = [
    (Path(__file__).parent / "assets" / name).read_text().strip()
    for name in ["bg_example_1.svg", "bg_example_2.svg"]
]


def _add_fonts(pdf: fpdf.FPDF) -> Tuple[str, List[str]]:
    @dataclasses.dataclass
    class FontFamilyEntry:
        name: str
        regular: str
        bold: str = None
        italic: str = None
        bold_italic: str = None

    def _add_family(entry: FontFamilyEntry, pdf: fpdf.FPDF):
        pdf.add_font(family=entry.name, style="", fname=str(FONTS_DIR / entry.regular))
        if entry.bold:
            pdf.add_font(family=entry.name, style="B", fname=str(FONTS_DIR / entry.bold))
        if entry.italic:
            pdf.add_font(family=entry.name, style="I", fname=str(FONTS_DIR / entry.italic))
        if entry.bold_italic:
            pdf.add_font(family=entry.name, style="BI", fname=str(FONTS_DIR / entry.bold_italic))

    main_font = FontFamilyEntry(
        name="NotoSans",
        regular="NotoSans-Regular.ttf",
        bold="NotoSans-Bold.ttf",
        italic="NotoSans-Italic.ttf",
        bold_italic="NotoSans-BoldItalic.ttf",
    )
    _add_family(main_font, pdf)

    fallbacks_fonts = [
        # Color emojis font (fpdf2 doesn't support color emojis)
        FontFamilyEntry(
            name="TwitterColorEmoji",
            regular="TwitterColorEmoji-SVGinOT.ttf",
        ),
        # Simplified Chinese
        FontFamilyEntry(
            name="NotoSansSJKcs",
            regular="NotoSansCJKsc-Regular.otf",
            bold="NotoSansCJKsc-Bold.otf",
        ),
        # Common fallback font
        FontFamilyEntry(
            name="DejaVuSans",
            regular="DejaVuSans.ttf",
        ),
        # FontFamilyEntry(
        #     name="NotoSansArabic",
        #     regular="NotoSansArabic-Regular.ttf",
        #     bold="NotoSansArabic-Bold.ttf",
        # ),
        # FontFamilyEntry(
        #     name="NotoSansHebrew",
        #     regular="NotoSansHebrew-Regular.ttf",
        #     bold="NotoSansHebrew-Bold.ttf",
        # ),
        # FontFamilyEntry(
        #     name="NotoSansMath",
        #     regular="NotoSansMath-Regular.ttf",
        # ),
    ]
    for entry in fallbacks_fonts:
        _add_family(entry, pdf)

    return main_font.name, [entry.name for entry in fallbacks_fonts]


def _convert_hsl_to_rgb_in_svg(svg_content):
    def _hsl_to_rgb(h, s, l):
        h, s, l = h / 360, s / 100, l / 100

        if s == 0:
            r = g = b = l
        else:
            q = l * (1 + s) if l < 0.5 else l + s - l * s
            p = 2 * l - q

            def hue_to_rgb(p, q, t):
                t = t % 1
                if t < 1 / 6: return p + (q - p) * 6 * t
                if t < 1 / 2: return q
                if t < 2 / 3: return p + (q - p) * (2 / 3 - t) * 6
                return p

            r = hue_to_rgb(p, q, h + 1 / 3)
            g = hue_to_rgb(p, q, h)
            b = hue_to_rgb(p, q, h - 1 / 3)

        return int(r * 255), int(g * 255), int(b * 255)

    return re.sub(
        r'hsl\(\s*(\d+)\s*,\s*(\d+)%\s*,\s*(\d+)%\s*\)',
        lambda m: 'rgb({}, {}, {})'.format(*_hsl_to_rgb(*map(int, m.groups()))),
        svg_content
    )


def _reduce_svg_opacity(svg_str, divisor: float = 10):
    ET.register_namespace('', 'http://www.w3.org/2000/svg')
    ET.register_namespace('xlink', 'http://www.w3.org/1999/xlink')
    ET.register_namespace('svgjs', 'http://svgjs.dev/svgjs')
    root = ET.fromstring(svg_str)

    def _process(val: str):
        try:
            return str(max(0., min(1., float(val) / divisor)))
        except:
            return val

    for elem in root.iter():
        for attr in ['opacity', 'fill-opacity', 'stroke-opacity', 'stop-opacity']:
            if attr in elem.attrib:
                elem.attrib[attr] = _process(elem.attrib[attr])

        if 'style' in elem.attrib:
            style = elem.attrib['style']
            for prop in ['opacity', 'fill-opacity', 'stroke-opacity', 'stop-opacity']:
                style = re.sub(rf'{prop}\s*:\s*([\d.]+)',
                               lambda m: f'{prop}:{_process(m.group(1))}', style)
            elem.attrib['style'] = style

    return ET.tostring(root, encoding='unicode')


def _svg_wrapper(content: str) -> io.BytesIO:
    buffer = io.BytesIO()
    content = _reduce_svg_opacity(content)
    content = _convert_hsl_to_rgb_in_svg(content)
    buffer.write(content.encode())
    buffer.seek(0)
    return buffer


class PDFWithBackground(fpdf.FPDF):
    def __init__(
            self,
            margin_x: int,
            margin_y: int,
            footer_h: int,
            *args,
            **kwargs,
    ):
        super().__init__(*args, **kwargs)
        self._background_svg = None
        self._footer_h = footer_h
        self._margin_x = margin_x
        self._margin_y = margin_y

    def set_page_background(self, svg: str):
        self._background_svg = svg

    def header(self):
        if self._background_svg:
            with self.local_context(fill_opacity=0.1):
                self.image(_svg_wrapper(self._background_svg), x=0, y=0, w=self.w, h=self.h)

    def footer(self):
        self.set_y(-self._margin_y - self._footer_h)
        self.set_draw_color(255, 45, 32)
        self.line(self._margin_x, self.get_y(), self.w - self._margin_x, self.get_y())
        if self.page_no() > 1:
            self.ln(5)
            footer_y = self.h - self._margin_y - self._footer_h
            logo_h = self._footer_h - (self.get_y() - footer_y)
            self.image(_svg_wrapper(REFACT_LOGO_SMALL_SVG), x=self._margin_x, y=self.get_y(), h=logo_h)


def generate_pdf(
        report_data: Dict[str, Any],
        company_logo: Optional[str] = None,
        margin_x: int = 25,
        margin_y: int = 25,
        footer_h: int = 12,
) -> bytes:
    """
    Generate PDF from report data.

    Expected report_data format:
    {
        "frontpage": [
            {"m_type": "text", "m_content": "markdown text"},
            {"m_type": "image", "m_content": "data:image/png;base64,iVBORw0KGgo..."},
        ],
        "sections": {
            "Section Name": [
                {"m_type": "text", "m_content": "markdown text"},
                {"m_type": "image", "m_content": "image source"}
            ]
        }
    }

    Supported image formats: png, jpg, jpeg, gif
    """
    pdf = PDFWithBackground(format="A4", margin_x=margin_x, margin_y=margin_y, footer_h=footer_h)
    pdf.set_margins(margin_x, margin_y, margin_x)
    pdf.set_compression(True)
    pdf.set_auto_page_break(auto=True, margin=margin_y + footer_h)

    font_family, fallback_fonts = _add_fonts(pdf)
    pdf.set_font(font_family, size=11)
    pdf.set_fallback_fonts(fallback_fonts)

    def _render_items(items: List[Dict[str, str]]):
        for item in items:
            if item["m_type"] == "text":
                _add_markdown(item["m_content"])
            elif item["m_type"] == "image":
                _add_image(item["m_content"])
            pdf.ln(5)

    def _add_markdown(md_text: str):
        html = markdown(md_text).encode("utf-8", errors="ignore").decode("utf-8")

        face = FontFace(family=font_family, size_pt=11, color=(0, 0, 0))
        bold = FontFace(family=font_family, size_pt=11, color=(0, 0, 0), emphasis="B")
        italic = FontFace(family=font_family, size_pt=11, color=(0, 0, 0), emphasis="I")
        mono = FontFace(family="Courier", size_pt=10, color=(0, 0, 0))

        tag_styles = {
            "p": face,
            "li": face,
            "pre": TextStyle(font_family="Courier", font_size_pt=10, t_margin=3, b_margin=1),
            "h1": FontFace(family=font_family, size_pt=18, emphasis="B", color=(0, 0, 0)),
            "h2": FontFace(family=font_family, size_pt=16, emphasis="B", color=(0, 0, 0)),
            "h3": FontFace(family=font_family, size_pt=14, emphasis="B", color=(0, 0, 0)),
            "strong": bold,
            "em": italic,
            "code": mono,
        }

        pdf.set_font(font_family)
        pdf.set_font_size(11)

        # NOTE: ordered list has issues with leading numbers
        html = html.replace("<ol>", "<ul>")
        html = html.replace("</ol>", "</ul>")

        # TODO: tables also have an issue with font size

        pdf.write_html(html, tag_styles=tag_styles)

    def _add_image(src: str, wh_mm: tuple[int, int] = (80, 80), raise_invalid: bool = False):
        try:
            match = re.match(r'data:image/(\w+);base64,(.+)', src)
            if not match:
                raise ValueError(f"[invalid format: {src[:50]}...]")
            img_format, base64_data = match.groups()

            img = Image.open(io.BytesIO(base64.b64decode(base64_data)))
            scale = max(img.width / wh_mm[0], img.height / wh_mm[1])
            w_mm, h_mm = img.width / scale, img.height / scale

            y_pos = pdf.get_y()
            space_left = pdf.h - y_pos - margin_y

            if h_mm > space_left:
                pdf.add_page()
                y_pos = pdf.get_y()

            buffer = io.BytesIO(base64.b64decode(base64_data))
            x_pos = (pdf.w - w_mm) / 2
            pdf.image(buffer, x=x_pos, y=y_pos, w=w_mm)

            pdf.set_draw_color(0, 0, 0)
            pdf.rect(x_pos, y_pos, w_mm, h_mm, "D")

            pdf.set_y(y_pos + h_mm + 5)

        except Exception as e:
            if raise_invalid:
                raise e

            pdf.set_fill_color(255, 245, 245)
            pdf.set_draw_color(255, 200, 200)
            pdf.set_text_color(150, 50, 50)
            pdf.set_font(font_family, "I", 10)

            y_before = pdf.get_y()
            pdf.rect(margin_x, y_before, pdf.w - margin_x * 2, margin_y, "FD")

            pdf.set_xy(30, y_before + 5)
            pdf.set_font(font_family, "B", 10)
            pdf.cell(0, 5, "Image Loading Error", new_x=fpdf.XPos.LMARGIN, new_y=fpdf.YPos.NEXT)

            pdf.set_x(30)
            pdf.set_font(font_family, "", 9)
            error_text = src[:80] + "..." if len(src) > 80 else src
            pdf.multi_cell(pdf.w - 60, 4, f"Source: {error_text}")

            pdf.set_text_color(0, 0, 0)
            pdf.set_y(y_before + 30)

    def _render_frontpage(
            items: List[Dict[str, str]],
            bg_svg_content: str,
    ):
        pdf.set_page_background(bg_svg_content)
        pdf.add_page()

        pdf.set_y(margin_y)
        pdf.set_font(font_family, "B", 28)
        pdf.set_text_color(0, 0, 0)

        footer_h = 20
        logo_w, logo_h = 85, 15
        pdf.cell(100, footer_h, "Report", align="L", new_x=fpdf.XPos.RIGHT)
        try:
            if not company_logo:
                raise ValueError("No company logo provided")
            match = re.match(r'data:image/(\w+);base64,(.+)', company_logo)
            if not match:
                logo_image = _svg_wrapper(company_logo)
            else:
                base64_data = match.groups()[1]
                logo_image = Image.open(io.BytesIO(base64.b64decode(base64_data)))
                scale = max(logo_image.width // logo_w, logo_image.height // logo_h)
                logo_w, logo_h = logo_image.width // scale, logo_image.height // scale

        except Exception:
            logo_image = _svg_wrapper(REFACT_LOGO_SVG)

        pdf.image(logo_image, x=pdf.w - margin_x - logo_w, y=pdf.get_y(), h=logo_h)

        pdf.set_y(pdf.get_y() + 20)
        pdf.set_draw_color(255, 45, 32)
        pdf.line(margin_x, pdf.get_y() + 5, pdf.w - margin_x, pdf.get_y() + 5)
        pdf.ln(20)

        _render_items(items)

    def _render_section(
            title: str,
            items: List[Dict[str, str]],
            bg_svg_content: str,
            _page_num: int,  # unused rn
    ):
        pdf.set_page_background(bg_svg_content)
        pdf.add_page()

        pdf.set_y(margin_y)
        pdf.set_font(font_family, "B", 22)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 15, title, align="L")

        pdf.set_draw_color(255, 45, 32)
        pdf.line(margin_x, pdf.get_y() + 2, pdf.w - margin_x, pdf.get_y() + 2)
        pdf.ln(15)

        pdf.set_font(font_family, "", 11)
        if not items:
            pdf.set_font(font_family, "I", 11)
            pdf.set_text_color(128, 128, 128)
            pdf.multi_cell(0, 8, "(No content in this section)")
            pdf.set_text_color(0, 0, 0)
        else:
            _render_items(items)

        pdf.section_title = None

    page_num = 0
    if frontpage := report_data.get("frontpage", []):
        page_num += 1
        _render_frontpage(frontpage, BACKGROUND_SVGS[0])

    for section_name, section_items in report_data.get("sections", {}).items():
        page_num += 1
        background_idx = page_num % (len(BACKGROUND_SVGS) - 1) + 1
        _render_section(section_name, section_items, BACKGROUND_SVGS[background_idx], page_num)

    return bytes(pdf.output())



IMAGE_PNG_BASE64 = "iVBORw0KGgoAAAANSUhEUgAABAAAAAMACAYAAAC6uhUNAAAACXBIWXMAAAAAAAAAAQCEeRdzAAAQAElEQVR4nO3d21njVhhAUfekntwTPdETGWEUZNnmNjBYZ6+HlS8zBhHy9m+dy+Hp6fEJAAAAGNvht/8DAAAAgJ8nAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAAAAAECAAAAAAQIAAAAABAgAAAAAAAAQIAAAAABAgAAAAAECAAAAAAQIAAAAAAAAECAAAAAAQIAAAAABAgAAAAAECAAAAAAAABAgAADObx8eHpcDg8e3z8zuc+/shzAYB/QwAAgIHMw//Dwx/H6eTh+Pznv33u8zMfTmHhO58LAPw7AgAADOR4PD4dp+np8c+APpuH9dMb+78b1udnTNMpKqyf+9u/LwDwcQIAAAxkGwAW89995Y39sp1gennzvw0Lv/37AgAfJwAAwEBOAeBwEQBOWwI+t2x/Hv7n5/2/7P9KAPjblQUAwL8jAADAQG4FgPOh/TTcv2d+1rzsf37eevgXAABgnwQAABjIOgA8zcP5PMxvhvbP2G4nWJ4nAADA/ggAADCQ9RkASwBYD+2z48thfqd/Pw355393/uf18C8AAMB+CQAAMJBrAeDyQMDD2Wn+pwhwWP359vAvAADAfgkAADCQjwSA9XC/XgWwDQDbpf8CAADsmwAAAAO5dQ3grQCwvP0/XwFweejf7QMFBQAA2AsBAAAGsgSA7RL+91cAHC4+e2v4n79eAACAfREAAGAgz1f3HQ4feou/DQAf+frXVQNWAADA3ggAADCAeRBf3v4vb/N/0rIFYP6Zj4+///sDAO8TAABgAHMAmAfyW0v4l7//6Fv+975++Wyatxs8WAUAAHsgAADAANYB4NrAPn+2+EgEWH/9WwHgKAAAwG4IAAAwgCUALAcAbvf0f0cAWJ8XsJjPGxAAAGAfBAAAGMB2C8B2+f70TQFgywoAANgPAQAABvDeFoCvBoB5j//bNwIIAACwFwIAAOzc8+n/x+P/WwCWbQDrQf/a0L8e8reD/rVVBNs3/8tVgPP3nm4DEAIA4J4JAACwc/Mb+NlbWwDeuspvmj52O8C15f/LVYDzzxcAAOC+CQAAMID3tgC8tdT/s99z8f22AADALggAALBz8xv46eVt/PMb/cPh4haA7b799QF/y0qA92LA+S0Aq+8RAABgFwQAANi5ZQvA7Pk8gCtnANwa6LfL+z+yBWB+/rQa/i39B4B9EAAAYCBLAPjqkv6PnANwtoLA8A8AuyEAAMBglvMA/nZ//1uDv2X/ALA/AgAADGi5FeD4wRP+31/2f7hY+v/bvyMA8DkCAAAMan0w4GcjwPl1f4cz08vVf5b/A8C+CAAAMKg5AHxlBcCy3P/kcHao4JozAABgXwQAABjMPJQ/3wjwMsB/ddn/W/4PAy+3D/z27wwAvE8AAIDBLIcAzkP6dx4CeG1bwOQ2AADYDQEAAAazBIBlWP/rAPDyjGvnASwrAUQAALh/AgAADGYdAL7j7f/2NgDnAQDAPgkAADCYnwoA2+H/UQAAgF0RAABgMN++BeDGwYDrGwMEAAC4fwIAAAzmpw8B3G4JWM4BOB6PbgQAgDsmAADAYF4DwOdWALz1tW8P/683AswR4Ld/fwDgOgEAAAazBICvnAOwHvJvLf1fD//bKwEFAAC4XwIAAAxmvQLg4uC+zcB/vDrcT2dnCKyf8XYUmAQAALhjAgAADOY8AJy/rd+aDpefXQaAVTzYhIDzLQECAADcMwEAAAaz3gKwDgDLYX3T9DrUv0aCdSy4HgAubgFYXQVoCwAA3D8BAAAGsw0A22X7x1UAmG4M9+fx4Pry/4uwIAAAwF0TAABgMNsAcG2v/rL0fzpc3xqwXT1wa9//xTOPx+ef/9v/DwCASwIAAAxmHQCmw+Ub/FsBYP02//r2gdsxYHnW8nNFAAC4PwIAAAzm1gqAdQA4rIb1WysA1rbbAW6vGJgEAAC4UwIAAAxkHrwfHh5uXv23DQAPm8/OBvp3lv1fO1dgjgQCAADcJwEAAAYy78E/u7bvjz//uBkAls9n2wCwDgfXDgDcbidYCAAAcJ8EAAAYyPz2/3WZ/vEsBKzf1q8DwHa4nzafXfuaawcKPq8AcAggANwtAQAABnJa/v/6pv+4ub5vGdi3AWCJBssb/OVsgLeG//MAcBr+55//2/8PAIDrBAAAGMz6EMB/yZt/ALhvAgAADGYexH/W4w0CAADcMwEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAweB7bQAAB3lJREFUAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAIEAAAAAAgQAAAAACBAAAAAAIAAAQAAAAACBAAAAAAIEAAAAAAgQAAAAACAAAEAAAAAAgQAAAAACBAAAAAAIEAAAAAAgAABAAAAAAL+A6Ax34sCR/LcAAAAAElFTkSuQmCC"
IMAGE_JPEG_BASE64 = "/9j//gARTGF2YzU4LjEzNC4xMDAA/9sAQwAIBgYHBgcICAgICAgJCQkKCgoJCQkJCgoKCgoKDAwMCgoKCgoKCgwMDAwNDg0NDQwNDg4PDw8SEhERFRUVGRkf/8QAlgABAAICAwEAAAAAAAAAAAAAAAYHBQgCAwQBAQEAAwEBAAAAAAAAAAAAAAAAAwQCAQUQAQACAgIBBAEDAgQHAQAAAAABAgMEBRESIRMxBhRBIgcjJFFzMjSxkWJhsja0UhEBAAICAQMCBAQEBAcBAAAAAAECAxEhQRIxBHGBYVEiE6EykTPBQtHSUnKys4JzI+EU8LH/wAARCAMABAADARIAAhIAAxIA/9oADAMBAAIRAxEAPwC+R4okAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHi5flNfhdDY39mZjDgrFreMTM/utFax1ETPra0R8ejBfyP/wCo8t/l4f8A6cTVKTe0VjzLWCvdftnrW8fvSSI3MRHmZ1+7WP8AiU/11/3Q7/rn2ynNT+Nta8cfyEU9ydX3rZ8V6eVo719m2HXjPNaxFsta0icXlXy9JiUB57HTZ08Objdq+rsa9KbFdrBaJmM+CfPxib1vXxtekRkjq9LV/b4s6i1e6kzaOu41Me8RNuJ3xO0OHLOG8WiInzExPiYnzEtZcN8M6tHtMeJ+PHL08uOMtJpO4idePPE7XC19y/Zft1NjZxV+y8nb2tGmzWPxuO8rWv7URT/Y9Wj+p81+fj5SO1z0nXdjpH3Rud5P09eO7p7/AAeQv/8AoY/81/3r/hWz9r+66/13Jh0tfDXkuV2KxkxcfXP7PWGMuOl8+xljHn9jHFb2tSb4/wCp7d607mED4TjMWH8rkeU2su1yOfHN77OeOr2nwt41n260x464u56iK168pjuY771Wle21727K1+W5tP0rHG/34QZs05ZjiK1rGq1jeoj+89Z6qVMd8torWN/PpHzmXqYcNMMar18zPmVq8JzGrz2hi39Xy9rJbNSPOs1mL6+fJgy16n/85cdoif1iO4Rf+Jpi31XHMTExPI8tMTHrExPJbHrEpbR2z53GomPa0bj8pdv/AE/9PH/w6vKmJiZifMTMT7w1l/iZP9dv90pwMjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArb+Xt+lNXiOPnZpWm5v8Aht635FcXvav4uzePd7+MfvYqzFrR4+depn5ZX759L2/tNcGfU3/xtjT6ya+KcOt7d80RlpM5c2TBnyeM4st6xj6mnfr6TPaTHF+zJasW326ia13zNq8R89T76ax5KRS1L1m0W86tPy19vEeY8pfTanPTevM+flWf5sY7TjyVvHSfp06/krDmeV5jQvwePi9HHbFsZb128eDDbZpgxUy4a91vgitaV6tfu0xEf8mU4XksO9i2NOLZcG5p3y4NnBlx6+LZwZK5L08r4cU5cMfuiZrMeVLdd9eqvhx4r0yze3bNa7pG4jc6njnz08OZcNsFo7oiYnmJjfbaPlPD08tslZx9lYmJtEW4mZiJ68fHy7izUzV3WfeJ1uPeOXrw5+L2dvJOHJpZtvF5Uye3bDfYx+ExW1L+Mzkr4zMRaJ66n0l5dTgvw9n8mm5nnJkva+3a2LU8tyeorj92a4K+37dIrH9vGKL9eVom0zLE471iLTW0RPiZiYid/SWrZe6O3tjUfpj7vs53Pbu3Xr3bai9LTNYtWZjzETG4+DlcfbO9zuf1T9v3cajf29OmtMT9c5rluS4bNscnp4fettXwRgy/2lLYPapPd4yxk77mbx1Mfuj9Onb9r+xanH6d4pe2XNH761w4cOfqI9O597+n4+vrMdz1Ew16nHixXiMV++O3e9xPO544Zw44y3is2ivvOuviPPP0Y9PkyZKTOSvbPdrWpjjUfVJe3ZWZ1NtdI8/yTL+Id3HTDyvHfk639HbjLh1cW1TP4Vz44zZbY4jqfG2W82tEd1rM/p8Mn/GX1bLwnG5N7ey6e1v8nkjayZNWmP2cdZpFMdMFowYJiPainuR4+uSLT3Pfa1eLzhxWvWe77omZjUzrXbv4fV31F44xViYrj3HMzO5+vMz8Hm+qrWua3b1iJmN+Jne/7or3nJe1582/KOkdOidCAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHTtTNdfNMTMTGK8xMekxMVn1iTc/22f/Jyf+EgCj/p9/yeJx7uTL7+zuz+TtZpiPK+xlrW2TymIiP9UzPpEREzMfPaIfTOZ3tfhqW15wZMOvGT3MF7XnJSa9R5WtFJmKX+aV7jqfT467x6mZnNk30tNY+UROoiPZY9ZiifVREzMRfXOt8+OPHy3y9b08RGHHr/ACVn4zHKP0tt+nrMR4ieJmenz5/8LMvSuStqWjutomsx/jEx1Px6oNT7Pu8hTLmx5tbHi88cYpmPbnFknBS8+uSl5v8A6/8Ap7jusx0pJ7Y6UtWJm1p3zER51kmv13EzEePzWGYmef56+kePl7sty3HYdKMVdHXpjyZrdekTMft678q+Xlaep6pFZj1+fSfTB8Pzt+QwYr7Wxa+X8PBWIyXinnmyU8clqRT58omJmP2xMx6/4TDNrW8zM+8zP/3RJ6jHXHktWOl7cc6ivE1//Za4Yw27sdLW53SJ+nMx/dMf4w5fc4vnI4PLv482ln1c2eMd60r7G17uK9a4r1t65Nmc+W+St5ve00jrrqUS1NjjOK+w8DsZqfiYqcnjvk29nYpFKVra9rXtby6mOp6m2Tqf+ETUm2XD+nnHMRuNbmup/VrnVdRqWfRVmZy+P4doiOs7jpCl67FWlq2r/VvfnW+Pznnfss+u1+BOt/073Gue6PnLZR8iYtETExMTHcTHrExP6xLg8wfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY3n9bc2+K3MOjm/H2b4usWX58ZiYmfTxv35Via9devf6fLJNY5rW0TaNxHT4cfmy7GtxvxuN+3VxQk/XfseHisulqfTdnXvfzjumTjMdZrMV67mN63UzavlaK06j/AL/MX23FInJS9s8W12zMz+JM8dI3XxvwwvR63FWJiMdqx0iIrr9tqLXXi/qX23ivr2vx+H6nnnepbYyZdn3eOiMmS17e1Fr13otakY5iL90i37K1iemxSb1FaZ803nLHb9sa1fcV1zr7defHuhWvT+ppgxdvZabczPjUz06/TXRVa96P0vl9Lj9PFj+m7uPbx4sNdjPS/Ff1MmOnU3i078Wnyt3buYrMNhEmWLZb2/79e2bT2xM5NRE/8uo44lGt4fU4cVIj8O0TqO6YivM+/duefCo1+0v43+xfYeUjX5XR2+M4+cHh+RltoWyxFuozUpOvk2Ji+SIi1fOvt909evSJ2BWKUr6akT+JWbb5jHaJ7rRO673zFY8TrztXW83rK5KzFaTuYmN2iOInzrUyqOOOkYqUpHfVKxWO/nqsderkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/Z"
IMAGE_GIF_BASE64 = "R0lGODlhAAQAA4QRAP//zMyZZplmMwAAAGYzM8zMmWYzAGZmZpmZmTMAAP/MmTMzM8zMzMxmM2ZmM5mZZplmZv///////////////////////////////////////////////////////////yH5BAEKAB8ALAAAAAAABAADAAX+ICCOZGmeaKqubOu+cCzPdG3feK7vfO//wKBwSCwaj8ikcslsOp/QqHRKrVqv2Kx2y+16v+CweEwum8/otHrNbrvf8Lh8Tq/b7/i8fs/v+/+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/wADChxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatzIsaPHjyBDihxJsqTJkyj+U6pcybKly5cwY8qcSbOmzZs4c+rcybOnz59AgwodSrSo0aNIkypdyrSp06dQo0qdSrWq1atYs2rdyrWr169gw4odS7as2bNo06pdy7at27dw48qdS7eu3bt48+rdy7ev37+AAwseTLiw4cOIEytezLix48eQI0ueTLmy5cuYM2vezLmz58+gQ4seTbq06dOoU6tezbq169ewY8ueTbu27du4c+vezbu379/AgwsfTry48ePIkytfzry58+fQo0ufTr269evYs2vfzr279+/gw4sfT768+fPo06tfz769+/fw48ufT7++/fv48+vfz7+///8ABijggAQWaOCBCCb+qOCCDDbo4IMQRijhhBRWaOGFGGao4YYcdujhhyCGKOKIJJZo4okopqjiiiy26OKLMMYo44w01mjjjTjmqOOOPPbo449ABinkkEQWaeSRSCap5JJMNunkk1BGKeWUVFZp5ZVYZqnlllx26eWXYIYp5phklmnmmWimqeaabLbp5ptwxinnnHTWaeedeOap55589unnn4AGKuighBZq6KGIJqrooow26uijkEYq6aSUVmrppZhmqummnHbq6aeghirqqKSWauqpqKaq6qqsturqq7DGKuustNZq66245qrrrrz26uuvwAYr7LDEFmvsscgmq+yyzDbr7LPQRivttNT+Vmvttdhmq+223Hbr7bfghivuuOSWa+656Kar7rrstuvuu/DGK++89NZr77345qvvvvz26++/AAcs8MAEF2zwwQgnrPDCDDfs8MMQRyzxxBRXbPHFGGes8cYcd+zxxyCHLPLIJJds8skop6zyyiy37PLLMMcs88w012zzzTjnrPPOPPfs889ABy300EQXbfTRSCet9NJMN+3001BHLfXUVFdt9dVYZ6311lx37fXXYIctNn0FDDAAAzIwYDbaYwdTAAICCPAAAjAggMAActPd9i8HEBBAAAIMUMALAywgAOAD7M23338HQIDeKpSdwOGIK+7LAQY0DjgEkJ9QwAH+eFMe+OCW74K55ogzUMDqrLN+wAIGUI446aXncroCCvwduNm892424wHkPnrtuvQdPO6AC0BA3AYQsLzyz/+N/PDE42I88o3HDrgBmSsft/TTC1699X5jr/vhAjQP+PKN4y68+OPbYjzqyQfAfffa0099/LT0/b3m30tf92QHQAPAj3+zOEAC8qc/7hEQdc07IAJf8TkCZI5+GMyg7gZwALZN0BVl+9/5HghAEZ5vAZ374CpCiDrekfBvvENd3B6nQhAOYHn5c2EGY7i9+yUghTVERQjjRrkEmO2FAeAhEWcIxCCagoWaMyLedlg4DNLQiak4AOic9z8Cmm0BC2j+HBFH6LzCHYB2WCSF3UJnQjEWDolLJAAHEYDGNI4CihqcogY1N4Am2hEUrzPbAh8oxwEgTo8FjGAf/2gKuyHAfy8UXSSVZ0Q6MhIV89vjHpVntjpekhRlQ6QmxVhIP35yFHdj3yiT17xKnnIVCziiJol4PwMk4IyvTMUCVKlB6DVvifvLpSjeZsFRAnOJzbObMO84AAauMnnMs6UEl9mJIT7zbw3o4f3k6ElqZgKP12QeMKfpzW+K8pnpI2ID4kbOcl7CmteEZgC56U5OlM2ZqxxjNAlwAFPWMxJl4yUGSRhAAXLvlv805zn1Bzh5RlOACE3oO28YOxM6II6hq6j+Q5V3AIlO1HkOXOIgZxg69q2zoTPsqEcrEUoLco8Au4QeSOU4Q2A2YJ22VOlKJ9FSaHLRcEukKPto+dKI7lQSLY3jAicXVJcec4a37OZRFxHKBAyVAEvdJ0VrCUxptnOqiUgq+grJRnbyzoLPI+IN6QnWRrxtjLor5ANGOICLPnWGFvxqWwvhP+nF1WzHU2sJ04nV++l1r4NAwPIgIMlCjtCIg4Vq83CJ2EUggLEEcEDysApYx6VPlhvFKj/9WdlBhNJ3qE2tag9bWtO27rWwjW0BGEDb2kq1tbjNrW53y9ve+va3wA2ucIdL3OIa97jITa5yl8vc5jr3udCNrnT+p0vd6lr3utjNrna3y93ueve74A2veMdL3vKa97zoTa9618ve9rr3vfCNr3znS9/62ve++M2vfvfL3/76978ADrCAB0zgAhv4wAhOsIIXzOAGO/jBEI6whCdM4Qpb+MIYzrCGN8zhDnv4wyAOsYhHTOISm/jEKE6xilfM4ha7+MUwjrGMZ0zjGtv4xjjOsY53zOMe+/jHQA6ykIdM5CIb+chITrKSl8zkJjv5yVCOspSnTOUqW/nKWM6ylrfM5S57+ctgDrOYx0zmMpv5zGhOs5rXzOY2u/nNcI6znOdM5zrb+c54zrOe98znPvv5z4AOtKAHTehCG/rQiE60ohfRzehGO/rRkI60pCdN6Upb+tKYzrSmN83pTnv606AOtahHTepSm/rUqE61qlfN6la7+tWwjrWsZ03rWtv61rjOta53zete+/rXwA62sIdN7GIb+9jITrayl83sZjv72dCOtrSnTe1qW/va2M62trfN7W57+9vgDre4x03ucpv73OhOt7rXze52u/vd8I63vOdN73rb+974zre+983vfvv73wAPuMAHTvCCG/zgCE+4whfO8IY7/OEQj7jEJ07xilv84hjPuMY3zvGOe/zjIJ9aCAAAOw=="


if __name__ == "__main__":
    def _text(t):
        return {"m_type": "text", "m_content": t}

    def _image(im):
        return {"m_type": "image", "m_content": im}

    report_data = {
        "frontpage": [
            _text("# Test Report\n\nThis is a **test** report with various image formats."),
        ],
        "sections": {
            "Key Themes And Frequency": [
                _text("## Key Themes And Frequency\n\n**Note: This is a sample report with placeholder content.**\n\n### Most Common Ad Themes (By Frequency)\n1. **Cost savings/ROI** - 78% of competitor ads\n2. **Ease of use** - 65% of competitor ads\n3. **Integration capabilities** - 52% of competitor ads\n4. **Customer testimonials** - 48% of competitor ads\n5. **Time savings** - 43% of competitor ads\n\n### Theme Distribution By Competitor\n| Competitor | Primary Theme | Secondary Theme | Tertiary Theme |\n|------------|---------------|-----------------|----------------|\n| Company A  | Cost savings  | Time savings    | Ease of use    |\n| Company B  | Testimonials  | Integration     | Support        |\n| Company C  | Ease of use   | ROI metrics     | Features       |"),
            ],
            "Font": [
                _text("## Testing non unicode characters, emojis and font style."),
                _text("Plain ASCII text: Hello, world!"),
                _text("Unicode with accents: café, naïve, résumé, jalapeño"),
                _text("Emojis: 😀 🚀 ❤️ 🎉 🐍"),
                _text("Bold: **bold text**"),
                _text("Italic: _italic text_"),
                _text("Monospace: `code font`"),
                _text("Mixed: **Bold and emoji 😀**"),
                _text("Right-to-left: שלום, مرحبا"),
                _text("Chinese: 你好，世界！"),
                _text("Cyrillic: Привет, мир!"),
                _text("Math symbols: ∑ ∏ ∫ ∂ ∇ ∆ ∞ ≈ ≠ ≤ ≥"),
                _text("Greek letters: α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω"),
                _text("Greek uppercase: Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω"),
                _text("Math operators: ± × ÷ √ ∛ ∜ ⊕ ⊗ ⊙ ⊘"),
                _text("Set theory: ∈ ∉ ⊂ ⊃ ⊆ ⊇ ∪ ∩ ∅ ℕ ℤ ℚ ℝ ℂ"),
                _text("Logic symbols: ∧ ∨ ¬ ⇒ ⇔ ∀ ∃ ∄"),
                _text("Arrows: → ← ↑ ↓ ↔ ⇐ ⇒ ⇔ ↦ ⟶ ⟵"),
                _text("Fractions and special: ½ ⅓ ¼ ⅔ ¾ ⅛ ℮ ℏ ℵ ℶ"),
                _text("Subscripts and superscripts: x² x³ x⁴ x⁵ x⁶ x⁷ x⁸ x⁹ x⁰ x₁ x₂ x₃ x₄ x₅"),
                _text("Complex equations: E = mc², ∫₀^∞ e^(-x²) dx = √π/2"),
            ],
            "Markdown": [
                _text("## Testing markdown features."),
                _text("**This is bold text**"),
                _text("_This text is italicized_"),
                _text("~~This was mistaken text~~"),
                _text("**This text is _extremely_ important**"),
                _text("***All this text is important***"),
                _text("This is a <sub>subscript</sub> text"),
                _text("This is an <ins>underlined</ins> text"),
            ],
            "Images": [
                _text("## Testing base64 encoded images"),
                _text("png image:"),
                _image(f"data:image/png;base64,{IMAGE_PNG_BASE64}"),
                _text("jpg image:"),
                _image(f"data:image/jpeg;base64,{IMAGE_JPEG_BASE64}"),
                _text("gif image:"),
                _image(f"data:image/gif;base64,{IMAGE_GIF_BASE64}"),
                _text("end images"),
            ],
            "Invalid Images": [
                _text("## Testing error handling"),
                _image("data:image/jpeg;base64,invalid_base64_data"),
                _text("text between images"),
                _image("https://file-examples.com/storage/fe180a8b03688f5559b9baf/2017/10/file_example_PNG_500kB.png"),
            ],
            "A lot of symbols in title: ijbflk;jndfevk;nadfkvlnad;kfvna;kdfjnva;kdsfjna;ksdjnvqa;ksdjnva;kjsdna": [
                * [_text("A lot of cells")] * 100,
                _text("Long celll: kjdsnvk;ajsdnk;jasndvk;ajnds;vknasd;kvjnads;kjvna;kdsjvnak;sdjnvakd;sjnvas"),
            ],
        },
    }

    # pdf_bytes = generate_pdf(report_data, company_logo=f"data:image/png;base64,{IMAGE_PNG_BASE64}")
    # pdf_bytes = generate_pdf(report_data, company_logo=REFACT_LOGO_SMALL_SVG)
    pdf_bytes = generate_pdf(report_data)
    with open("test.pdf", "wb") as f:
        f.write(pdf_bytes)
    print("PDF generated successfully!")
